### ISSUE TITLE
Request: Easier access to the php.ini / Are the docs correct?

### ISSUE THREAD

**Issue by mannp** [LycheeOrg/Lychee-Laravel-Docker#19]
The docs refer to the php.ini used in the docker and the location appears incorrect compared to the actual docker.

/etc/php/7.3/php/ does not exist, it appears to be /7.3/cli or fpm?

Cheers

drwxr-xr-x 1 root root  26 Aug 16 11:41 cli/php.ini
drwxr-xr-x 1 root root  62 Aug 15 21:50 fpm/php.ini
drwxr-xr-x 1 root root 698 Aug 15 21:50 mods-available

**Comment by mannp** [comment]
Not sure how easy it is to incorporate but a .user.ini could override the php.ini settings so we could just add the overrides to that file ...

**Comment by Chostakovitch** [comment]
Hey, good catch, the path was indeed incorrect. 

> Not sure how easy it is to incorporate but a .user.ini could override the php.ini settings so we could just add the overrides to that file ...

This is true, overriding all php.ini is kind of brutal. See PR #21 and tell me what you think!

**Comment by mannp** [comment]
For me nginx may accept uploads of 100M but FPM doesn't.

If I recall it was some figure like 8m or even lower, so the initial experience for me was nothing uploaded except for the smallest of files.

So its not so much an advanced thing, but a basic necessity for the default config.

Perhaps the basic config should be brought into more of a norm so that users do not have to mess with advanced settings.

Replacing nginx.conf or php.ini doesn't matter to me :)

**Comment by Chostakovitch** [comment]
> but arn't you replacing all of the nginx.conf, which is equally brutal :)

Right, but at least you can take the configuration already made for Lychee as a base.

Anyway, the primary goal of this PR is to make PHP accept uploads of 100Mo without having to modify the base configuration ; this is done [here](https://github.com/LycheeOrg/Lychee-Laravel-Docker/pull/21/files#diff-a7401aa8222eac0519710478bac133d8R75). This is the reason I used "advanced config" as a name because the initial configuration should fit your needs.

What do you think ? Is it an acceptable solution ?

**Comment by mannp** [comment]
Hi @Chostakovitch if the default config now allows for uploading all but the largest videos etc then it works for me :)

I expect it will help others who'd expect the majority of pictures, perhaps less than 20m per file, would upload without a problem.

**Comment by Chostakovitch** [comment]
@mannp yup, to be more precise (I should have been more explicit in the PR description), the default config have [these parameters](https://github.com/LycheeOrg/Lychee/wiki/FAQ#i-cant-upload-photos) set : 

```
max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 20M
memory_limit = 256M
```

**Comment by roblandry** [comment]
Does [#21] solve your initial problem? I believe this issue can be closed. I will reopen if further corrections need to be made.
