### ISSUE TITLE
Database [mariadb] not configured

### ISSUE THREAD

**Issue by samcro1967** [LycheeOrg/Lychee-Laravel-Docker#27]
I am getting an error trying to get this container to work with mariadb.  Below is the Docker command I ran to create the container.  I am able to connect to my mariadb container with other applications using the user ID and password so I feel confident it is working fine.  There is a DB call lychee in mariadb already.

docker create --name=lychee /
-e TZ=America/Chicago /
-p 8597:80 /
-e PUID=1000 -e PGID=1000 /
-e DB_CONNECTION=mariadb /
-e DB_HOST=192.168.1.103 /
-e DB_PORT=3306 /
-e DB_DATABASE=lychee /
-e DB_USERNAME=<user_name>/
-e DB_PASSWORD=<password> /
-v /docker/lychee:/conf -v /pictures:/uploads /
bigrob8181/lychee-laravel

**Comment by d7415** [comment]
- What's the error you're getting?
- Have you tried `DB_CONNECTION=mysql`?
- Are you using "the `mysql_native_password` authentication plugin" as described in the [README](https://github.com/LycheeOrg/Lychee-Laravel-Docker#run-with-docker)?

**Comment by tmp-hallenser** [comment]
my guess would be DB_HOST is wrong

**Comment by samcro1967** [comment]
DB host is definitely correct.  The same settings work for other containers with mariadb,

Maybe I am confused. I thought DB_CONNECTION should equal mariadb since I am using mariadb.  Changing it to mysql gets a bit farther.

I will have to figure out hot to run the command in the mariadb container later today to see if that gets me further.

lychee web page now has a different error.
(3/3) QueryException SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee.sym_links' doesn't exist (SQL: select * from `sym_links` where `created_at` < 2020-01-31 18:58:47)

Docker logs are as follows:
**** Make sure the /conf and /uploads folders exist ****
**** Create the symbolic link for the /uploads folder ****
**** Copy the .env to /conf ****
**** Inject .env values ****
**** Generate the key (to make sure that cookies cannot be decrypted etc) ****
Application key set successfully.
**** Migrate the database ****
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.18 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0 seconds)
Migrating: 2018_08_03_110935_create_albums_table

In Connection.php line 665:

  SQLSTATE[HY000]: General error: 1025 Error on rename of './lychee/albums' t
  o './lychee/#sql2-251-a' (errno: 168 "Unknown (generic) error from engine")
   (SQL: alter table `albums` add constraint `albums_parent_id_foreign` forei
  gn key (`parent_id`) references `albums` (`id`))


In PDOStatement.php line 119:

  SQLSTATE[HY000]: General error: 1025 Error on rename of './lychee/albums' t
  o './lychee/#sql2-251-a' (errno: 168 "Unknown (generic) error from engine")


In PDOStatement.php line 117:

  SQLSTATE[HY000]: General error: 1025 Error on rename of './lychee/albums' t
  o './lychee/#sql2-251-a' (errno: 168 "Unknown (generic) error from engine")


**** Create user and use PUID/PGID ****
-e      User UID :      1000
-e      User GID :      1000
**** Set Permissions ****

**Comment by d7415** [comment]
That's a weird error, and I'm not sure what it's saying about rename - that migration should only create a table. It's probably not a good thing that the script seems to continue if the migrate fails, but it still looks like a connection problem. Then again, the commands are the same as for the apparently successful `users` table creation...

**Comment by samcro1967** [comment]
The syntax of the command does not work on the most recent version of mariadb.  Appreciate the suggestions.
