### ISSUE TITLE
Docker container wont start

### ISSUE THREAD

**Issue by herohamp** [LycheeOrg/Lychee-Laravel-Docker#36]
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file
/entrypoint.sh: 7: /entrypoint.sh: cannot open /var/www/html/Lychee-Laravel/.git/refs/heads/master: No such file

**Comment by d7415** [comment]
Where are you puling the image from? Or are you building it yourself?
