### ISSUE TITLE
Allow Travis to pass for PRs by making login/push conditional

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-Laravel-Docker#43]

**Comment by d7415** [comment]
I've just reminded myself why this is an issue. At the moment we push to Docker Hub and then pull back down to test.
To achieve this goal we'd need to redesign the testing steps to get the images from the build step without Docker Hub in the middle.

**Comment by roblandry** [comment]
It's not possible to have both multi arch and test without first pushing to dockerhub. That's required for multi arch. You cannot test multiarch following the build until you pull the correct arch from docker hub.
