### ISSUE TITLE
Error:Class 'Predis\Client' not found

### ISSUE THREAD

**Issue by SionInory** [LycheeOrg/Lychee-Laravel-Docker#53]
OS:raspberry 4B arm64
docker:lycheeorg/lychee-laravel:latest

In the file '.env' 'CACHE_DRIVER=redis' then appears an error

ErrorClass 'Predis\Client' not found
--
in PredisConnector.php line 29
at PredisConnector->connect(array('host' => '127.0.0.1', 'password' => null, 'port' => 6379, 'database' => 0), array())in RedisManager.php line 110

**Comment by d7415** [comment]
The redis functionality hasn't been heavily (if at all) tested in Lychee. 

Starting with the basics, have you set up a redis server and configured its details in `.env`?

**Comment by SionInory** [comment]
Because I cannot configure the id of database in .env,I configured it in the /config/database.php.

In the .env,If CACHE_DRIVER=file,the website runs ok.If CACHE_DRIVER=redis,the page of gallery will be white and appear this error.

**Comment by d7415** [comment]
Right. Looking more closely, it looks like a missing dependency upstream. I'm not going to get to it right now, but LycheeOrg/Lychee#566.

**Comment by d7415** [comment]
Hi. If you're happy enough working in the docker container, could you try `apt install -y php-redis` and see if that works? It [looks](https://laravel.com/docs/7.x/redis) like that's an acceptable (and more maintained) alternative to `predis`.

**Comment by SionInory** [comment]
Yes,when I use PhpRedis,the error will disappear.Thank you very much.

**Comment by d7415** [comment]
Thanks for testing! This should be in the next release (hopefully today or tomorrow)
