### ISSUE TITLE
404 after update

### ISSUE THREAD

**Issue by pchampio** [LycheeOrg/Lychee-Laravel-Docker#55]
I've pulled the latest `lycheeorg/lychee-laravel:dev` image, and my lychee website suddenly stopped working. `404 Not Found nginx/1.14.2`.

Tried `lycheeorg/lychee-laravel:testing` got the same result.

docker logs showed no error, the last line is:
`lychee_laravel           | **** Setup complete, starting the server. **** 
`
and inside the container /var/log/nginx/error.log` showed no errors.

Failling back to an older tag worked: `lycheeorg/lychee-laravel:dev@sha256:2e54f47ee8cf5458505ea456b17375ca0de36d3d3aa87e1bc77f90e15cb70f8c` (Commit: https://github.com/LycheeOrg/Lychee/commit/499eef635f8e019d5f7018eea27e0360c42ccdac)

I don't know if this issue is related to the docker repo or the php repo, sorry if I posed the issue in the wrong place.

**Comment by d7415** [comment]
Thanks for using `:dev`! Are you using a custom `nginx.conf`? Lychee has moved to `/var/www/html/Lychee` now.

I'd forgotten that use case - I'll add a symlink to the image. That should hopefully be in place by the end of the weekend and *will* be in place before the next release.

**Comment by d7415** [comment]
The ':dev' image should refresh in about 30mins, at which point this will hopefully be fixed!
