### ISSUE TITLE
Not able to run lychee with docker-compose example

### ISSUE THREAD

**Issue by vkentta** [LycheeOrg/Lychee-Laravel-Docker#57]
Using this example file https://github.com/LycheeOrg/Lychee-Laravel-Docker/blob/master/docker-compose.yml and running `docker compose up` I got the following logs initially:

```
...
**** Migrate the database ****
In Connection.php line 669:
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s
chema.tables where table_schema = lychee and table_name = migrations and ta
ble_type = 'BASE TABLE')
In PDOConnection.php line 31: 
SQLSTATE[HY000] [2002] Connection refused
In PDOConnection.php line 27:
SQLSTATE[HY000] [2002] Connection refused
**** Create user and use PUID/PGID ****
-e      User UID :      1000
-e      User GID :      1000
**** Set Permissions ****
**** Setup complete, starting the server. ****
```

If I do `docker compose down` + `docker compose up` again, it seems to run the migrations successfully.

If I do `docker compose down` + `docker compose up` one more time after that, it seems to boot saying there is nothing to migrate.

Each time I still get nothing on http://localhost:80

**Comment by d7415** [comment]
Starting with the basics, did you set the passwords in that example, and do `MYSQL_PASSWORD` and `DB_PASSWORD` match?

**Comment by d7415** [comment]
Trying to get Travis testing this, it may just be docker-compose starting lychee too quickly. Unfortunately it doesn't look like there's an easy fix to that without changing the main Lychee Docker image. I might try adding an environment variable...

**Comment by tmp-hallenser** [comment]
I've used this approach in the past: https://medium.com/@krishnaregmi/wait-for-it-docker-compose-f0bac30f3357

**Comment by d7415** [comment]
I thought about that, but that would make the Docker image messy for non-composer users.

My current thinking is an `ARG` in the Dockerfile and have it sleep for that many (default 0) seconds before running.

I'm a little tempted to release a second docker-compose.yml with sqlite setup, but it feels fairly pointless for that use case!

**Comment by vkentta** [comment]
@d7415 Yeah the passwords did match indeed. A detail that might be related here is that I was running that on windows machine.

**Comment by d7415** [comment]
I think #59 should fix the `:dev` image when I merge it later. Hoping to do a release today too which should fix `:latest`
